-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.loginServer.loginServer.bank.c2s_pb')


DEPOSIT = protobuf.Descriptor();
local DEPOSIT_AMOUNT_FIELD = protobuf.FieldDescriptor();
WITHDRAW = protobuf.Descriptor();
local WITHDRAW_AMOUNT_FIELD = protobuf.FieldDescriptor();
QUERY = protobuf.Descriptor();

DEPOSIT_AMOUNT_FIELD.name = "amount"
DEPOSIT_AMOUNT_FIELD.full_name = ".loginServer.bank.c2s.Deposit.amount"
DEPOSIT_AMOUNT_FIELD.number = 1
DEPOSIT_AMOUNT_FIELD.index = 0
DEPOSIT_AMOUNT_FIELD.label = 2
DEPOSIT_AMOUNT_FIELD.has_default_value = false
DEPOSIT_AMOUNT_FIELD.default_value = 0
DEPOSIT_AMOUNT_FIELD.type = 4
DEPOSIT_AMOUNT_FIELD.cpp_type = 4

DEPOSIT.name = "Deposit"
DEPOSIT.full_name = ".loginServer.bank.c2s.Deposit"
DEPOSIT.nested_types = {}
DEPOSIT.enum_types = {}
DEPOSIT.fields = {DEPOSIT_AMOUNT_FIELD}
DEPOSIT.is_extendable = false
DEPOSIT.extensions = {}
WITHDRAW_AMOUNT_FIELD.name = "amount"
WITHDRAW_AMOUNT_FIELD.full_name = ".loginServer.bank.c2s.Withdraw.amount"
WITHDRAW_AMOUNT_FIELD.number = 1
WITHDRAW_AMOUNT_FIELD.index = 0
WITHDRAW_AMOUNT_FIELD.label = 2
WITHDRAW_AMOUNT_FIELD.has_default_value = false
WITHDRAW_AMOUNT_FIELD.default_value = 0
WITHDRAW_AMOUNT_FIELD.type = 4
WITHDRAW_AMOUNT_FIELD.cpp_type = 4

WITHDRAW.name = "Withdraw"
WITHDRAW.full_name = ".loginServer.bank.c2s.Withdraw"
WITHDRAW.nested_types = {}
WITHDRAW.enum_types = {}
WITHDRAW.fields = {WITHDRAW_AMOUNT_FIELD}
WITHDRAW.is_extendable = false
WITHDRAW.extensions = {}
QUERY.name = "Query"
QUERY.full_name = ".loginServer.bank.c2s.Query"
QUERY.nested_types = {}
QUERY.enum_types = {}
QUERY.fields = {}
QUERY.is_extendable = false
QUERY.extensions = {}

Deposit = protobuf.Message(DEPOSIT)
Query = protobuf.Message(QUERY)
Withdraw = protobuf.Message(WITHDRAW)

