-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.loginServer.loginServer.tuijianren.c2s_pb')


UPTUIJIANREN = protobuf.Descriptor();
local UPTUIJIANREN_GAMEID_FIELD = protobuf.FieldDescriptor();
local UPTUIJIANREN_KINDID_FIELD = protobuf.FieldDescriptor();
INTOTUIJIANREN = protobuf.Descriptor();
RECVBOX = protobuf.Descriptor();
RECVSCORE = protobuf.Descriptor();

UPTUIJIANREN_GAMEID_FIELD.name = "gameId"
UPTUIJIANREN_GAMEID_FIELD.full_name = ".loginServer.tuijianren.c2s.UpTuijianren.gameId"
UPTUIJIANREN_GAMEID_FIELD.number = 1
UPTUIJIANREN_GAMEID_FIELD.index = 0
UPTUIJIANREN_GAMEID_FIELD.label = 1
UPTUIJIANREN_GAMEID_FIELD.has_default_value = false
UPTUIJIANREN_GAMEID_FIELD.default_value = 0
UPTUIJIANREN_GAMEID_FIELD.type = 5
UPTUIJIANREN_GAMEID_FIELD.cpp_type = 1

UPTUIJIANREN_KINDID_FIELD.name = "kindId"
UPTUIJIANREN_KINDID_FIELD.full_name = ".loginServer.tuijianren.c2s.UpTuijianren.kindId"
UPTUIJIANREN_KINDID_FIELD.number = 2
UPTUIJIANREN_KINDID_FIELD.index = 1
UPTUIJIANREN_KINDID_FIELD.label = 1
UPTUIJIANREN_KINDID_FIELD.has_default_value = false
UPTUIJIANREN_KINDID_FIELD.default_value = 0
UPTUIJIANREN_KINDID_FIELD.type = 5
UPTUIJIANREN_KINDID_FIELD.cpp_type = 1

UPTUIJIANREN.name = "UpTuijianren"
UPTUIJIANREN.full_name = ".loginServer.tuijianren.c2s.UpTuijianren"
UPTUIJIANREN.nested_types = {}
UPTUIJIANREN.enum_types = {}
UPTUIJIANREN.fields = {UPTUIJIANREN_GAMEID_FIELD, UPTUIJIANREN_KINDID_FIELD}
UPTUIJIANREN.is_extendable = false
UPTUIJIANREN.extensions = {}
INTOTUIJIANREN.name = "IntoTuijianren"
INTOTUIJIANREN.full_name = ".loginServer.tuijianren.c2s.IntoTuijianren"
INTOTUIJIANREN.nested_types = {}
INTOTUIJIANREN.enum_types = {}
INTOTUIJIANREN.fields = {}
INTOTUIJIANREN.is_extendable = false
INTOTUIJIANREN.extensions = {}
RECVBOX.name = "RecvBox"
RECVBOX.full_name = ".loginServer.tuijianren.c2s.RecvBox"
RECVBOX.nested_types = {}
RECVBOX.enum_types = {}
RECVBOX.fields = {}
RECVBOX.is_extendable = false
RECVBOX.extensions = {}
RECVSCORE.name = "RecvScore"
RECVSCORE.full_name = ".loginServer.tuijianren.c2s.RecvScore"
RECVSCORE.nested_types = {}
RECVSCORE.enum_types = {}
RECVSCORE.fields = {}
RECVSCORE.is_extendable = false
RECVSCORE.extensions = {}

IntoTuijianren = protobuf.Message(INTOTUIJIANREN)
RecvBox = protobuf.Message(RECVBOX)
RecvScore = protobuf.Message(RECVSCORE)
UpTuijianren = protobuf.Message(UPTUIJIANREN)

