-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.loginServer.loginServer.match.c2s_pb')


MATCHSIGNUP = protobuf.Descriptor();
local MATCHSIGNUP_SERVERID_FIELD = protobuf.FieldDescriptor();
QUERYMATCHSERVERINFO = protobuf.Descriptor();
local QUERYMATCHSERVERINFO_SERVERID_FIELD = protobuf.FieldDescriptor();
CANCLESIGNUP = protobuf.Descriptor();
local CANCLESIGNUP_SERVERID_FIELD = protobuf.FieldDescriptor();

MATCHSIGNUP_SERVERID_FIELD.name = "ServerID"
MATCHSIGNUP_SERVERID_FIELD.full_name = ".loginServer.match.c2s.matchSignUp.ServerID"
MATCHSIGNUP_SERVERID_FIELD.number = 1
MATCHSIGNUP_SERVERID_FIELD.index = 0
MATCHSIGNUP_SERVERID_FIELD.label = 2
MATCHSIGNUP_SERVERID_FIELD.has_default_value = false
MATCHSIGNUP_SERVERID_FIELD.default_value = 0
MATCHSIGNUP_SERVERID_FIELD.type = 5
MATCHSIGNUP_SERVERID_FIELD.cpp_type = 1

MATCHSIGNUP.name = "matchSignUp"
MATCHSIGNUP.full_name = ".loginServer.match.c2s.matchSignUp"
MATCHSIGNUP.nested_types = {}
MATCHSIGNUP.enum_types = {}
MATCHSIGNUP.fields = {MATCHSIGNUP_SERVERID_FIELD}
MATCHSIGNUP.is_extendable = false
MATCHSIGNUP.extensions = {}
QUERYMATCHSERVERINFO_SERVERID_FIELD.name = "ServerID"
QUERYMATCHSERVERINFO_SERVERID_FIELD.full_name = ".loginServer.match.c2s.queryMatchServerInfo.ServerID"
QUERYMATCHSERVERINFO_SERVERID_FIELD.number = 1
QUERYMATCHSERVERINFO_SERVERID_FIELD.index = 0
QUERYMATCHSERVERINFO_SERVERID_FIELD.label = 3
QUERYMATCHSERVERINFO_SERVERID_FIELD.has_default_value = false
QUERYMATCHSERVERINFO_SERVERID_FIELD.default_value = {}
QUERYMATCHSERVERINFO_SERVERID_FIELD.type = 5
QUERYMATCHSERVERINFO_SERVERID_FIELD.cpp_type = 1

QUERYMATCHSERVERINFO.name = "queryMatchServerInfo"
QUERYMATCHSERVERINFO.full_name = ".loginServer.match.c2s.queryMatchServerInfo"
QUERYMATCHSERVERINFO.nested_types = {}
QUERYMATCHSERVERINFO.enum_types = {}
QUERYMATCHSERVERINFO.fields = {QUERYMATCHSERVERINFO_SERVERID_FIELD}
QUERYMATCHSERVERINFO.is_extendable = false
QUERYMATCHSERVERINFO.extensions = {}
CANCLESIGNUP_SERVERID_FIELD.name = "ServerID"
CANCLESIGNUP_SERVERID_FIELD.full_name = ".loginServer.match.c2s.cancleSignUp.ServerID"
CANCLESIGNUP_SERVERID_FIELD.number = 1
CANCLESIGNUP_SERVERID_FIELD.index = 0
CANCLESIGNUP_SERVERID_FIELD.label = 2
CANCLESIGNUP_SERVERID_FIELD.has_default_value = false
CANCLESIGNUP_SERVERID_FIELD.default_value = 0
CANCLESIGNUP_SERVERID_FIELD.type = 5
CANCLESIGNUP_SERVERID_FIELD.cpp_type = 1

CANCLESIGNUP.name = "cancleSignUp"
CANCLESIGNUP.full_name = ".loginServer.match.c2s.cancleSignUp"
CANCLESIGNUP.nested_types = {}
CANCLESIGNUP.enum_types = {}
CANCLESIGNUP.fields = {CANCLESIGNUP_SERVERID_FIELD}
CANCLESIGNUP.is_extendable = false
CANCLESIGNUP.extensions = {}

cancleSignUp = protobuf.Message(CANCLESIGNUP)
matchSignUp = protobuf.Message(MATCHSIGNUP)
queryMatchServerInfo = protobuf.Message(QUERYMATCHSERVERINFO)

