-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.loginServer.loginServer.message.c2s_pb')


QUERYEXCHANGEMESSAGE = protobuf.Descriptor();

QUERYEXCHANGEMESSAGE.name = "QueryExchangeMessage"
QUERYEXCHANGEMESSAGE.full_name = ".loginServer.message.c2s.QueryExchangeMessage"
QUERYEXCHANGEMESSAGE.nested_types = {}
QUERYEXCHANGEMESSAGE.enum_types = {}
QUERYEXCHANGEMESSAGE.fields = {}
QUERYEXCHANGEMESSAGE.is_extendable = false
QUERYEXCHANGEMESSAGE.extensions = {}

QueryExchangeMessage = protobuf.Message(QUERYEXCHANGEMESSAGE)

