-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.loginServer.loginServer.login.c2s_pb')


LOGIN = protobuf.Descriptor();
local LOGIN_SESSION_FIELD = protobuf.FieldDescriptor();
local LOGIN_NICKNAME_FIELD = protobuf.FieldDescriptor();
local LOGIN_MACHINEID_FIELD = protobuf.FieldDescriptor();
local LOGIN_KINDID_FIELD = protobuf.FieldDescriptor();
local LOGIN_SCORETAG_FIELD = protobuf.FieldDescriptor();
SIMULATORLOGIN = protobuf.Descriptor();
local SIMULATORLOGIN_SESSION_FIELD = protobuf.FieldDescriptor();
local SIMULATORLOGIN_NICKNAME_FIELD = protobuf.FieldDescriptor();
local SIMULATORLOGIN_MACHINEID_FIELD = protobuf.FieldDescriptor();
local SIMULATORLOGIN_KINDID_FIELD = protobuf.FieldDescriptor();
local SIMULATORLOGIN_SCORETAG_FIELD = protobuf.FieldDescriptor();

LOGIN_SESSION_FIELD.name = "session"
LOGIN_SESSION_FIELD.full_name = ".loginServer.login.c2s.Login.session"
LOGIN_SESSION_FIELD.number = 1
LOGIN_SESSION_FIELD.index = 0
LOGIN_SESSION_FIELD.label = 2
LOGIN_SESSION_FIELD.has_default_value = false
LOGIN_SESSION_FIELD.default_value = ""
LOGIN_SESSION_FIELD.type = 9
LOGIN_SESSION_FIELD.cpp_type = 9

LOGIN_NICKNAME_FIELD.name = "nickName"
LOGIN_NICKNAME_FIELD.full_name = ".loginServer.login.c2s.Login.nickName"
LOGIN_NICKNAME_FIELD.number = 2
LOGIN_NICKNAME_FIELD.index = 1
LOGIN_NICKNAME_FIELD.label = 2
LOGIN_NICKNAME_FIELD.has_default_value = false
LOGIN_NICKNAME_FIELD.default_value = ""
LOGIN_NICKNAME_FIELD.type = 9
LOGIN_NICKNAME_FIELD.cpp_type = 9

LOGIN_MACHINEID_FIELD.name = "machineID"
LOGIN_MACHINEID_FIELD.full_name = ".loginServer.login.c2s.Login.machineID"
LOGIN_MACHINEID_FIELD.number = 3
LOGIN_MACHINEID_FIELD.index = 2
LOGIN_MACHINEID_FIELD.label = 2
LOGIN_MACHINEID_FIELD.has_default_value = false
LOGIN_MACHINEID_FIELD.default_value = ""
LOGIN_MACHINEID_FIELD.type = 9
LOGIN_MACHINEID_FIELD.cpp_type = 9

LOGIN_KINDID_FIELD.name = "kindID"
LOGIN_KINDID_FIELD.full_name = ".loginServer.login.c2s.Login.kindID"
LOGIN_KINDID_FIELD.number = 4
LOGIN_KINDID_FIELD.index = 3
LOGIN_KINDID_FIELD.label = 3
LOGIN_KINDID_FIELD.has_default_value = false
LOGIN_KINDID_FIELD.default_value = {}
LOGIN_KINDID_FIELD.type = 5
LOGIN_KINDID_FIELD.cpp_type = 1

LOGIN_SCORETAG_FIELD.name = "scoreTag"
LOGIN_SCORETAG_FIELD.full_name = ".loginServer.login.c2s.Login.scoreTag"
LOGIN_SCORETAG_FIELD.number = 5
LOGIN_SCORETAG_FIELD.index = 4
LOGIN_SCORETAG_FIELD.label = 1
LOGIN_SCORETAG_FIELD.has_default_value = false
LOGIN_SCORETAG_FIELD.default_value = false
LOGIN_SCORETAG_FIELD.type = 8
LOGIN_SCORETAG_FIELD.cpp_type = 7

LOGIN.name = "Login"
LOGIN.full_name = ".loginServer.login.c2s.Login"
LOGIN.nested_types = {}
LOGIN.enum_types = {}
LOGIN.fields = {LOGIN_SESSION_FIELD, LOGIN_NICKNAME_FIELD, LOGIN_MACHINEID_FIELD, LOGIN_KINDID_FIELD, LOGIN_SCORETAG_FIELD}
LOGIN.is_extendable = false
LOGIN.extensions = {}
SIMULATORLOGIN_SESSION_FIELD.name = "session"
SIMULATORLOGIN_SESSION_FIELD.full_name = ".loginServer.login.c2s.SimulatorLogin.session"
SIMULATORLOGIN_SESSION_FIELD.number = 1
SIMULATORLOGIN_SESSION_FIELD.index = 0
SIMULATORLOGIN_SESSION_FIELD.label = 2
SIMULATORLOGIN_SESSION_FIELD.has_default_value = false
SIMULATORLOGIN_SESSION_FIELD.default_value = ""
SIMULATORLOGIN_SESSION_FIELD.type = 9
SIMULATORLOGIN_SESSION_FIELD.cpp_type = 9

SIMULATORLOGIN_NICKNAME_FIELD.name = "nickName"
SIMULATORLOGIN_NICKNAME_FIELD.full_name = ".loginServer.login.c2s.SimulatorLogin.nickName"
SIMULATORLOGIN_NICKNAME_FIELD.number = 2
SIMULATORLOGIN_NICKNAME_FIELD.index = 1
SIMULATORLOGIN_NICKNAME_FIELD.label = 2
SIMULATORLOGIN_NICKNAME_FIELD.has_default_value = false
SIMULATORLOGIN_NICKNAME_FIELD.default_value = ""
SIMULATORLOGIN_NICKNAME_FIELD.type = 9
SIMULATORLOGIN_NICKNAME_FIELD.cpp_type = 9

SIMULATORLOGIN_MACHINEID_FIELD.name = "machineID"
SIMULATORLOGIN_MACHINEID_FIELD.full_name = ".loginServer.login.c2s.SimulatorLogin.machineID"
SIMULATORLOGIN_MACHINEID_FIELD.number = 3
SIMULATORLOGIN_MACHINEID_FIELD.index = 2
SIMULATORLOGIN_MACHINEID_FIELD.label = 2
SIMULATORLOGIN_MACHINEID_FIELD.has_default_value = false
SIMULATORLOGIN_MACHINEID_FIELD.default_value = ""
SIMULATORLOGIN_MACHINEID_FIELD.type = 9
SIMULATORLOGIN_MACHINEID_FIELD.cpp_type = 9

SIMULATORLOGIN_KINDID_FIELD.name = "kindID"
SIMULATORLOGIN_KINDID_FIELD.full_name = ".loginServer.login.c2s.SimulatorLogin.kindID"
SIMULATORLOGIN_KINDID_FIELD.number = 4
SIMULATORLOGIN_KINDID_FIELD.index = 3
SIMULATORLOGIN_KINDID_FIELD.label = 3
SIMULATORLOGIN_KINDID_FIELD.has_default_value = false
SIMULATORLOGIN_KINDID_FIELD.default_value = {}
SIMULATORLOGIN_KINDID_FIELD.type = 5
SIMULATORLOGIN_KINDID_FIELD.cpp_type = 1

SIMULATORLOGIN_SCORETAG_FIELD.name = "scoreTag"
SIMULATORLOGIN_SCORETAG_FIELD.full_name = ".loginServer.login.c2s.SimulatorLogin.scoreTag"
SIMULATORLOGIN_SCORETAG_FIELD.number = 5
SIMULATORLOGIN_SCORETAG_FIELD.index = 4
SIMULATORLOGIN_SCORETAG_FIELD.label = 1
SIMULATORLOGIN_SCORETAG_FIELD.has_default_value = false
SIMULATORLOGIN_SCORETAG_FIELD.default_value = false
SIMULATORLOGIN_SCORETAG_FIELD.type = 8
SIMULATORLOGIN_SCORETAG_FIELD.cpp_type = 7

SIMULATORLOGIN.name = "SimulatorLogin"
SIMULATORLOGIN.full_name = ".loginServer.login.c2s.SimulatorLogin"
SIMULATORLOGIN.nested_types = {}
SIMULATORLOGIN.enum_types = {}
SIMULATORLOGIN.fields = {SIMULATORLOGIN_SESSION_FIELD, SIMULATORLOGIN_NICKNAME_FIELD, SIMULATORLOGIN_MACHINEID_FIELD, SIMULATORLOGIN_KINDID_FIELD, SIMULATORLOGIN_SCORETAG_FIELD}
SIMULATORLOGIN.is_extendable = false
SIMULATORLOGIN.extensions = {}

Login = protobuf.Message(LOGIN)
SimulatorLogin = protobuf.Message(SIMULATORLOGIN)

