-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.zhajinhua.zhajinhuabattle.c2s_pb')


CMD_C_SOFASIT_PRO = protobuf.Descriptor();
local CMD_C_SOFASIT_PRO_WSOFAID_FIELD = protobuf.FieldDescriptor();
CMD_C_PLACEJETTON_PRO = protobuf.Descriptor();
local CMD_C_PLACEJETTON_PRO_CBJETTONAREA_FIELD = protobuf.FieldDescriptor();
local CMD_C_PLACEJETTON_PRO_LJETTONSCORE_FIELD = protobuf.FieldDescriptor();
CMD_C_COMMON_PRO = protobuf.Descriptor();

CMD_C_SOFASIT_PRO_WSOFAID_FIELD.name = "wSofaID"
CMD_C_SOFASIT_PRO_WSOFAID_FIELD.full_name = ".zhajinhuabattle.c2s.CMD_C_SofaSit_Pro.wSofaID"
CMD_C_SOFASIT_PRO_WSOFAID_FIELD.number = 1
CMD_C_SOFASIT_PRO_WSOFAID_FIELD.index = 0
CMD_C_SOFASIT_PRO_WSOFAID_FIELD.label = 2
CMD_C_SOFASIT_PRO_WSOFAID_FIELD.has_default_value = false
CMD_C_SOFASIT_PRO_WSOFAID_FIELD.default_value = 0
CMD_C_SOFASIT_PRO_WSOFAID_FIELD.type = 5
CMD_C_SOFASIT_PRO_WSOFAID_FIELD.cpp_type = 1

CMD_C_SOFASIT_PRO.name = "CMD_C_SofaSit_Pro"
CMD_C_SOFASIT_PRO.full_name = ".zhajinhuabattle.c2s.CMD_C_SofaSit_Pro"
CMD_C_SOFASIT_PRO.nested_types = {}
CMD_C_SOFASIT_PRO.enum_types = {}
CMD_C_SOFASIT_PRO.fields = {CMD_C_SOFASIT_PRO_WSOFAID_FIELD}
CMD_C_SOFASIT_PRO.is_extendable = false
CMD_C_SOFASIT_PRO.extensions = {}
CMD_C_PLACEJETTON_PRO_CBJETTONAREA_FIELD.name = "cbJettonArea"
CMD_C_PLACEJETTON_PRO_CBJETTONAREA_FIELD.full_name = ".zhajinhuabattle.c2s.CMD_C_PlaceJetton_Pro.cbJettonArea"
CMD_C_PLACEJETTON_PRO_CBJETTONAREA_FIELD.number = 1
CMD_C_PLACEJETTON_PRO_CBJETTONAREA_FIELD.index = 0
CMD_C_PLACEJETTON_PRO_CBJETTONAREA_FIELD.label = 2
CMD_C_PLACEJETTON_PRO_CBJETTONAREA_FIELD.has_default_value = false
CMD_C_PLACEJETTON_PRO_CBJETTONAREA_FIELD.default_value = 0
CMD_C_PLACEJETTON_PRO_CBJETTONAREA_FIELD.type = 5
CMD_C_PLACEJETTON_PRO_CBJETTONAREA_FIELD.cpp_type = 1

CMD_C_PLACEJETTON_PRO_LJETTONSCORE_FIELD.name = "lJettonScore"
CMD_C_PLACEJETTON_PRO_LJETTONSCORE_FIELD.full_name = ".zhajinhuabattle.c2s.CMD_C_PlaceJetton_Pro.lJettonScore"
CMD_C_PLACEJETTON_PRO_LJETTONSCORE_FIELD.number = 2
CMD_C_PLACEJETTON_PRO_LJETTONSCORE_FIELD.index = 1
CMD_C_PLACEJETTON_PRO_LJETTONSCORE_FIELD.label = 2
CMD_C_PLACEJETTON_PRO_LJETTONSCORE_FIELD.has_default_value = false
CMD_C_PLACEJETTON_PRO_LJETTONSCORE_FIELD.default_value = 0
CMD_C_PLACEJETTON_PRO_LJETTONSCORE_FIELD.type = 3
CMD_C_PLACEJETTON_PRO_LJETTONSCORE_FIELD.cpp_type = 2

CMD_C_PLACEJETTON_PRO.name = "CMD_C_PlaceJetton_Pro"
CMD_C_PLACEJETTON_PRO.full_name = ".zhajinhuabattle.c2s.CMD_C_PlaceJetton_Pro"
CMD_C_PLACEJETTON_PRO.nested_types = {}
CMD_C_PLACEJETTON_PRO.enum_types = {}
CMD_C_PLACEJETTON_PRO.fields = {CMD_C_PLACEJETTON_PRO_CBJETTONAREA_FIELD, CMD_C_PLACEJETTON_PRO_LJETTONSCORE_FIELD}
CMD_C_PLACEJETTON_PRO.is_extendable = false
CMD_C_PLACEJETTON_PRO.extensions = {}
CMD_C_COMMON_PRO.name = "CMD_C_Common_Pro"
CMD_C_COMMON_PRO.full_name = ".zhajinhuabattle.c2s.CMD_C_Common_Pro"
CMD_C_COMMON_PRO.nested_types = {}
CMD_C_COMMON_PRO.enum_types = {}
CMD_C_COMMON_PRO.fields = {}
CMD_C_COMMON_PRO.is_extendable = false
CMD_C_COMMON_PRO.extensions = {}

CMD_C_Common_Pro = protobuf.Message(CMD_C_COMMON_PRO)
CMD_C_PlaceJetton_Pro = protobuf.Message(CMD_C_PLACEJETTON_PRO)
CMD_C_SofaSit_Pro = protobuf.Message(CMD_C_SOFASIT_PRO)

