-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.common.common.misc.s2c_pb')


SYSTEMMESSAGE = protobuf.Descriptor();
local SYSTEMMESSAGE_TYPE_FIELD = protobuf.FieldDescriptor();
local SYSTEMMESSAGE_MSG_FIELD = protobuf.FieldDescriptor();

SYSTEMMESSAGE_TYPE_FIELD.name = "type"
SYSTEMMESSAGE_TYPE_FIELD.full_name = ".common.misc.s2c.SystemMessage.type"
SYSTEMMESSAGE_TYPE_FIELD.number = 1
SYSTEMMESSAGE_TYPE_FIELD.index = 0
SYSTEMMESSAGE_TYPE_FIELD.label = 2
SYSTEMMESSAGE_TYPE_FIELD.has_default_value = false
SYSTEMMESSAGE_TYPE_FIELD.default_value = 0
SYSTEMMESSAGE_TYPE_FIELD.type = 13
SYSTEMMESSAGE_TYPE_FIELD.cpp_type = 3

SYSTEMMESSAGE_MSG_FIELD.name = "msg"
SYSTEMMESSAGE_MSG_FIELD.full_name = ".common.misc.s2c.SystemMessage.msg"
SYSTEMMESSAGE_MSG_FIELD.number = 2
SYSTEMMESSAGE_MSG_FIELD.index = 1
SYSTEMMESSAGE_MSG_FIELD.label = 2
SYSTEMMESSAGE_MSG_FIELD.has_default_value = false
SYSTEMMESSAGE_MSG_FIELD.default_value = ""
SYSTEMMESSAGE_MSG_FIELD.type = 9
SYSTEMMESSAGE_MSG_FIELD.cpp_type = 9

SYSTEMMESSAGE.name = "SystemMessage"
SYSTEMMESSAGE.full_name = ".common.misc.s2c.SystemMessage"
SYSTEMMESSAGE.nested_types = {}
SYSTEMMESSAGE.enum_types = {}
SYSTEMMESSAGE.fields = {SYSTEMMESSAGE_TYPE_FIELD, SYSTEMMESSAGE_MSG_FIELD}
SYSTEMMESSAGE.is_extendable = false
SYSTEMMESSAGE.extensions = {}

SystemMessage = protobuf.Message(SYSTEMMESSAGE)

