-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.loginServer.loginServer.ranking.c2s_pb')


QUERYWEALTHRANKING = protobuf.Descriptor();
QUERYLOVELINESRANKING = protobuf.Descriptor();

QUERYWEALTHRANKING.name = "QueryWealthRanking"
QUERYWEALTHRANKING.full_name = ".loginServer.ranking.c2s.QueryWealthRanking"
QUERYWEALTHRANKING.nested_types = {}
QUERYWEALTHRANKING.enum_types = {}
QUERYWEALTHRANKING.fields = {}
QUERYWEALTHRANKING.is_extendable = false
QUERYWEALTHRANKING.extensions = {}
QUERYLOVELINESRANKING.name = "QueryLoveLinesRanking"
QUERYLOVELINESRANKING.full_name = ".loginServer.ranking.c2s.QueryLoveLinesRanking"
QUERYLOVELINESRANKING.nested_types = {}
QUERYLOVELINESRANKING.enum_types = {}
QUERYLOVELINESRANKING.fields = {}
QUERYLOVELINESRANKING.is_extendable = false
QUERYLOVELINESRANKING.extensions = {}

QueryLoveLinesRanking = protobuf.Message(QUERYLOVELINESRANKING)
QueryWealthRanking = protobuf.Message(QUERYWEALTHRANKING)

