-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.loginServer.loginServer.activity.s2c_pb')


QUERYSCOREACTIVITY = protobuf.Descriptor();
local QUERYSCOREACTIVITY_ISALMSAVAILABLE_FIELD = protobuf.FieldDescriptor();
local QUERYSCOREACTIVITY_ISVIPFREESCOREAVAILABLE_FIELD = protobuf.FieldDescriptor();
ALMS = protobuf.Descriptor();
local ALMS_RETCODE = protobuf.EnumDescriptor();
local ALMS_RETCODE_RC_OK_ENUM = protobuf.EnumValueDescriptor();
local ALMS_CODE_FIELD = protobuf.FieldDescriptor();
local ALMS_ALMS_FIELD = protobuf.FieldDescriptor();
local ALMS_SCORE_FIELD = protobuf.FieldDescriptor();

QUERYSCOREACTIVITY_ISALMSAVAILABLE_FIELD.name = "isAlmsAvailable"
QUERYSCOREACTIVITY_ISALMSAVAILABLE_FIELD.full_name = ".loginServer.activity.s2c.QueryScoreActivity.isAlmsAvailable"
QUERYSCOREACTIVITY_ISALMSAVAILABLE_FIELD.number = 1
QUERYSCOREACTIVITY_ISALMSAVAILABLE_FIELD.index = 0
QUERYSCOREACTIVITY_ISALMSAVAILABLE_FIELD.label = 2
QUERYSCOREACTIVITY_ISALMSAVAILABLE_FIELD.has_default_value = false
QUERYSCOREACTIVITY_ISALMSAVAILABLE_FIELD.default_value = false
QUERYSCOREACTIVITY_ISALMSAVAILABLE_FIELD.type = 8
QUERYSCOREACTIVITY_ISALMSAVAILABLE_FIELD.cpp_type = 7

QUERYSCOREACTIVITY_ISVIPFREESCOREAVAILABLE_FIELD.name = "isVIPFreeScoreAvailable"
QUERYSCOREACTIVITY_ISVIPFREESCOREAVAILABLE_FIELD.full_name = ".loginServer.activity.s2c.QueryScoreActivity.isVIPFreeScoreAvailable"
QUERYSCOREACTIVITY_ISVIPFREESCOREAVAILABLE_FIELD.number = 2
QUERYSCOREACTIVITY_ISVIPFREESCOREAVAILABLE_FIELD.index = 1
QUERYSCOREACTIVITY_ISVIPFREESCOREAVAILABLE_FIELD.label = 2
QUERYSCOREACTIVITY_ISVIPFREESCOREAVAILABLE_FIELD.has_default_value = false
QUERYSCOREACTIVITY_ISVIPFREESCOREAVAILABLE_FIELD.default_value = false
QUERYSCOREACTIVITY_ISVIPFREESCOREAVAILABLE_FIELD.type = 8
QUERYSCOREACTIVITY_ISVIPFREESCOREAVAILABLE_FIELD.cpp_type = 7

QUERYSCOREACTIVITY.name = "QueryScoreActivity"
QUERYSCOREACTIVITY.full_name = ".loginServer.activity.s2c.QueryScoreActivity"
QUERYSCOREACTIVITY.nested_types = {}
QUERYSCOREACTIVITY.enum_types = {}
QUERYSCOREACTIVITY.fields = {QUERYSCOREACTIVITY_ISALMSAVAILABLE_FIELD, QUERYSCOREACTIVITY_ISVIPFREESCOREAVAILABLE_FIELD}
QUERYSCOREACTIVITY.is_extendable = false
QUERYSCOREACTIVITY.extensions = {}
ALMS_RETCODE_RC_OK_ENUM.name = "RC_OK"
ALMS_RETCODE_RC_OK_ENUM.index = 0
ALMS_RETCODE_RC_OK_ENUM.number = 1
ALMS_RETCODE.name = "RetCode"
ALMS_RETCODE.full_name = ".loginServer.activity.s2c.Alms.RetCode"
ALMS_RETCODE.values = {ALMS_RETCODE_RC_OK_ENUM}
ALMS_CODE_FIELD.name = "code"
ALMS_CODE_FIELD.full_name = ".loginServer.activity.s2c.Alms.code"
ALMS_CODE_FIELD.number = 1
ALMS_CODE_FIELD.index = 0
ALMS_CODE_FIELD.label = 2
ALMS_CODE_FIELD.has_default_value = false
ALMS_CODE_FIELD.default_value = nil
ALMS_CODE_FIELD.enum_type = ALMS.RETCODE
ALMS_CODE_FIELD.type = 14
ALMS_CODE_FIELD.cpp_type = 8

ALMS_ALMS_FIELD.name = "alms"
ALMS_ALMS_FIELD.full_name = ".loginServer.activity.s2c.Alms.alms"
ALMS_ALMS_FIELD.number = 2
ALMS_ALMS_FIELD.index = 1
ALMS_ALMS_FIELD.label = 1
ALMS_ALMS_FIELD.has_default_value = false
ALMS_ALMS_FIELD.default_value = 0
ALMS_ALMS_FIELD.type = 5
ALMS_ALMS_FIELD.cpp_type = 1

ALMS_SCORE_FIELD.name = "score"
ALMS_SCORE_FIELD.full_name = ".loginServer.activity.s2c.Alms.score"
ALMS_SCORE_FIELD.number = 3
ALMS_SCORE_FIELD.index = 2
ALMS_SCORE_FIELD.label = 1
ALMS_SCORE_FIELD.has_default_value = false
ALMS_SCORE_FIELD.default_value = 0
ALMS_SCORE_FIELD.type = 5
ALMS_SCORE_FIELD.cpp_type = 1

ALMS.name = "Alms"
ALMS.full_name = ".loginServer.activity.s2c.Alms"
ALMS.nested_types = {}
ALMS.enum_types = {ALMS_RETCODE}
ALMS.fields = {ALMS_CODE_FIELD, ALMS_ALMS_FIELD, ALMS_SCORE_FIELD}
ALMS.is_extendable = false
ALMS.extensions = {}

Alms = protobuf.Message(ALMS)
QueryScoreActivity = protobuf.Message(QUERYSCOREACTIVITY)

