-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.loginServer.loginServer.heartBeat.c2s_pb')


HEARTBEAT = protobuf.Descriptor();

HEARTBEAT.name = "HeartBeat"
HEARTBEAT.full_name = ".loginServer.heartBeat.c2s.HeartBeat"
HEARTBEAT.nested_types = {}
HEARTBEAT.enum_types = {}
HEARTBEAT.fields = {}
HEARTBEAT.is_extendable = false
HEARTBEAT.extensions = {}

HeartBeat = protobuf.Message(HEARTBEAT)

