-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.loginServer.loginServer.server.c2s_pb')


QUERYSERVERONLINE = protobuf.Descriptor();
local QUERYSERVERONLINE_SERVERIDLIST_FIELD = protobuf.FieldDescriptor();

QUERYSERVERONLINE_SERVERIDLIST_FIELD.name = "serverIDList"
QUERYSERVERONLINE_SERVERIDLIST_FIELD.full_name = ".loginServer.server.c2s.QueryServerOnline.serverIDList"
QUERYSERVERONLINE_SERVERIDLIST_FIELD.number = 1
QUERYSERVERONLINE_SERVERIDLIST_FIELD.index = 0
QUERYSERVERONLINE_SERVERIDLIST_FIELD.label = 3
QUERYSERVERONLINE_SERVERIDLIST_FIELD.has_default_value = false
QUERYSERVERONLINE_SERVERIDLIST_FIELD.default_value = {}
QUERYSERVERONLINE_SERVERIDLIST_FIELD.type = 13
QUERYSERVERONLINE_SERVERIDLIST_FIELD.cpp_type = 3

QUERYSERVERONLINE.name = "QueryServerOnline"
QUERYSERVERONLINE.full_name = ".loginServer.server.c2s.QueryServerOnline"
QUERYSERVERONLINE.nested_types = {}
QUERYSERVERONLINE.enum_types = {}
QUERYSERVERONLINE.fields = {QUERYSERVERONLINE_SERVERIDLIST_FIELD}
QUERYSERVERONLINE.is_extendable = false
QUERYSERVERONLINE.extensions = {}

QueryServerOnline = protobuf.Message(QUERYSERVERONLINE)

