-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.loginServer.loginServer.account.c2s_pb')


CHANGEFACEID = protobuf.Descriptor();
local CHANGEFACEID_FACEID_FIELD = protobuf.FieldDescriptor();
CHANGESIGNATURE = protobuf.Descriptor();
local CHANGESIGNATURE_SIGNATURE_FIELD = protobuf.FieldDescriptor();
CHANGENICKNAME = protobuf.Descriptor();
local CHANGENICKNAME_ISSCORECHARGED_FIELD = protobuf.FieldDescriptor();
local CHANGENICKNAME_NICKNAME_FIELD = protobuf.FieldDescriptor();
CHECKNICKNAME = protobuf.Descriptor();
local CHECKNICKNAME_NICKNAME_FIELD = protobuf.FieldDescriptor();
CHANGEGENDER = protobuf.Descriptor();
local CHANGEGENDER_GENDER_FIELD = protobuf.FieldDescriptor();
SETPLATFORMFACE = protobuf.Descriptor();
local SETPLATFORMFACE_PLATFORMFACE_FIELD = protobuf.FieldDescriptor();
SETBINDINGINFO = protobuf.Descriptor();

CHANGEFACEID_FACEID_FIELD.name = "faceID"
CHANGEFACEID_FACEID_FIELD.full_name = ".loginServer.account.c2s.ChangeFaceID.faceID"
CHANGEFACEID_FACEID_FIELD.number = 1
CHANGEFACEID_FACEID_FIELD.index = 0
CHANGEFACEID_FACEID_FIELD.label = 2
CHANGEFACEID_FACEID_FIELD.has_default_value = false
CHANGEFACEID_FACEID_FIELD.default_value = 0
CHANGEFACEID_FACEID_FIELD.type = 13
CHANGEFACEID_FACEID_FIELD.cpp_type = 3

CHANGEFACEID.name = "ChangeFaceID"
CHANGEFACEID.full_name = ".loginServer.account.c2s.ChangeFaceID"
CHANGEFACEID.nested_types = {}
CHANGEFACEID.enum_types = {}
CHANGEFACEID.fields = {CHANGEFACEID_FACEID_FIELD}
CHANGEFACEID.is_extendable = false
CHANGEFACEID.extensions = {}
CHANGESIGNATURE_SIGNATURE_FIELD.name = "signature"
CHANGESIGNATURE_SIGNATURE_FIELD.full_name = ".loginServer.account.c2s.ChangeSignature.signature"
CHANGESIGNATURE_SIGNATURE_FIELD.number = 1
CHANGESIGNATURE_SIGNATURE_FIELD.index = 0
CHANGESIGNATURE_SIGNATURE_FIELD.label = 2
CHANGESIGNATURE_SIGNATURE_FIELD.has_default_value = false
CHANGESIGNATURE_SIGNATURE_FIELD.default_value = ""
CHANGESIGNATURE_SIGNATURE_FIELD.type = 9
CHANGESIGNATURE_SIGNATURE_FIELD.cpp_type = 9

CHANGESIGNATURE.name = "ChangeSignature"
CHANGESIGNATURE.full_name = ".loginServer.account.c2s.ChangeSignature"
CHANGESIGNATURE.nested_types = {}
CHANGESIGNATURE.enum_types = {}
CHANGESIGNATURE.fields = {CHANGESIGNATURE_SIGNATURE_FIELD}
CHANGESIGNATURE.is_extendable = false
CHANGESIGNATURE.extensions = {}
CHANGENICKNAME_ISSCORECHARGED_FIELD.name = "isScoreCharged"
CHANGENICKNAME_ISSCORECHARGED_FIELD.full_name = ".loginServer.account.c2s.ChangeNickname.isScoreCharged"
CHANGENICKNAME_ISSCORECHARGED_FIELD.number = 1
CHANGENICKNAME_ISSCORECHARGED_FIELD.index = 0
CHANGENICKNAME_ISSCORECHARGED_FIELD.label = 2
CHANGENICKNAME_ISSCORECHARGED_FIELD.has_default_value = false
CHANGENICKNAME_ISSCORECHARGED_FIELD.default_value = false
CHANGENICKNAME_ISSCORECHARGED_FIELD.type = 8
CHANGENICKNAME_ISSCORECHARGED_FIELD.cpp_type = 7

CHANGENICKNAME_NICKNAME_FIELD.name = "nickName"
CHANGENICKNAME_NICKNAME_FIELD.full_name = ".loginServer.account.c2s.ChangeNickname.nickName"
CHANGENICKNAME_NICKNAME_FIELD.number = 2
CHANGENICKNAME_NICKNAME_FIELD.index = 1
CHANGENICKNAME_NICKNAME_FIELD.label = 2
CHANGENICKNAME_NICKNAME_FIELD.has_default_value = false
CHANGENICKNAME_NICKNAME_FIELD.default_value = ""
CHANGENICKNAME_NICKNAME_FIELD.type = 9
CHANGENICKNAME_NICKNAME_FIELD.cpp_type = 9

CHANGENICKNAME.name = "ChangeNickname"
CHANGENICKNAME.full_name = ".loginServer.account.c2s.ChangeNickname"
CHANGENICKNAME.nested_types = {}
CHANGENICKNAME.enum_types = {}
CHANGENICKNAME.fields = {CHANGENICKNAME_ISSCORECHARGED_FIELD, CHANGENICKNAME_NICKNAME_FIELD}
CHANGENICKNAME.is_extendable = false
CHANGENICKNAME.extensions = {}
CHECKNICKNAME_NICKNAME_FIELD.name = "nickName"
CHECKNICKNAME_NICKNAME_FIELD.full_name = ".loginServer.account.c2s.CheckNickname.nickName"
CHECKNICKNAME_NICKNAME_FIELD.number = 1
CHECKNICKNAME_NICKNAME_FIELD.index = 0
CHECKNICKNAME_NICKNAME_FIELD.label = 2
CHECKNICKNAME_NICKNAME_FIELD.has_default_value = false
CHECKNICKNAME_NICKNAME_FIELD.default_value = ""
CHECKNICKNAME_NICKNAME_FIELD.type = 9
CHECKNICKNAME_NICKNAME_FIELD.cpp_type = 9

CHECKNICKNAME.name = "CheckNickname"
CHECKNICKNAME.full_name = ".loginServer.account.c2s.CheckNickname"
CHECKNICKNAME.nested_types = {}
CHECKNICKNAME.enum_types = {}
CHECKNICKNAME.fields = {CHECKNICKNAME_NICKNAME_FIELD}
CHECKNICKNAME.is_extendable = false
CHECKNICKNAME.extensions = {}
CHANGEGENDER_GENDER_FIELD.name = "gender"
CHANGEGENDER_GENDER_FIELD.full_name = ".loginServer.account.c2s.ChangeGender.gender"
CHANGEGENDER_GENDER_FIELD.number = 1
CHANGEGENDER_GENDER_FIELD.index = 0
CHANGEGENDER_GENDER_FIELD.label = 2
CHANGEGENDER_GENDER_FIELD.has_default_value = false
CHANGEGENDER_GENDER_FIELD.default_value = 0
CHANGEGENDER_GENDER_FIELD.type = 5
CHANGEGENDER_GENDER_FIELD.cpp_type = 1

CHANGEGENDER.name = "ChangeGender"
CHANGEGENDER.full_name = ".loginServer.account.c2s.ChangeGender"
CHANGEGENDER.nested_types = {}
CHANGEGENDER.enum_types = {}
CHANGEGENDER.fields = {CHANGEGENDER_GENDER_FIELD}
CHANGEGENDER.is_extendable = false
CHANGEGENDER.extensions = {}
SETPLATFORMFACE_PLATFORMFACE_FIELD.name = "platformFace"
SETPLATFORMFACE_PLATFORMFACE_FIELD.full_name = ".loginServer.account.c2s.SetPlatformFace.platformFace"
SETPLATFORMFACE_PLATFORMFACE_FIELD.number = 1
SETPLATFORMFACE_PLATFORMFACE_FIELD.index = 0
SETPLATFORMFACE_PLATFORMFACE_FIELD.label = 2
SETPLATFORMFACE_PLATFORMFACE_FIELD.has_default_value = false
SETPLATFORMFACE_PLATFORMFACE_FIELD.default_value = ""
SETPLATFORMFACE_PLATFORMFACE_FIELD.type = 9
SETPLATFORMFACE_PLATFORMFACE_FIELD.cpp_type = 9

SETPLATFORMFACE.name = "SetPlatformFace"
SETPLATFORMFACE.full_name = ".loginServer.account.c2s.SetPlatformFace"
SETPLATFORMFACE.nested_types = {}
SETPLATFORMFACE.enum_types = {}
SETPLATFORMFACE.fields = {SETPLATFORMFACE_PLATFORMFACE_FIELD}
SETPLATFORMFACE.is_extendable = false
SETPLATFORMFACE.extensions = {}
SETBINDINGINFO.name = "SetBindingInfo"
SETBINDINGINFO.full_name = ".loginServer.account.c2s.SetBindingInfo"
SETBINDINGINFO.nested_types = {}
SETBINDINGINFO.enum_types = {}
SETBINDINGINFO.fields = {}
SETBINDINGINFO.is_extendable = false
SETBINDINGINFO.extensions = {}

ChangeFaceID = protobuf.Message(CHANGEFACEID)
ChangeGender = protobuf.Message(CHANGEGENDER)
ChangeNickname = protobuf.Message(CHANGENICKNAME)
ChangeSignature = protobuf.Message(CHANGESIGNATURE)
CheckNickname = protobuf.Message(CHECKNICKNAME)
SetBindingInfo = protobuf.Message(SETBINDINGINFO)
SetPlatformFace = protobuf.Message(SETPLATFORMFACE)

