-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.loginServer.loginServer.ping.s2c_pb')


PING = protobuf.Descriptor();

PING.name = "Ping"
PING.full_name = ".loginServer.ping.s2c.Ping"
PING.nested_types = {}
PING.enum_types = {}
PING.fields = {}
PING.is_extendable = false
PING.extensions = {}

Ping = protobuf.Message(PING)

