-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.zhajinhua.zhajinhua.c2s_pb')


CMD_C_ADDSCORE_PRO = protobuf.Descriptor();
local CMD_C_ADDSCORE_PRO_LSCORE_FIELD = protobuf.FieldDescriptor();
local CMD_C_ADDSCORE_PRO_WSTATE_FIELD = protobuf.FieldDescriptor();
CMD_C_COMPARECARD_PRO = protobuf.Descriptor();
local CMD_C_COMPARECARD_PRO_WCOMPAREUSER_FIELD = protobuf.FieldDescriptor();
CMD_C_COMMON_PRO = protobuf.Descriptor();

CMD_C_ADDSCORE_PRO_LSCORE_FIELD.name = "lScore"
CMD_C_ADDSCORE_PRO_LSCORE_FIELD.full_name = ".zhajinhua.c2s.CMD_C_AddScore_Pro.lScore"
CMD_C_ADDSCORE_PRO_LSCORE_FIELD.number = 1
CMD_C_ADDSCORE_PRO_LSCORE_FIELD.index = 0
CMD_C_ADDSCORE_PRO_LSCORE_FIELD.label = 2
CMD_C_ADDSCORE_PRO_LSCORE_FIELD.has_default_value = false
CMD_C_ADDSCORE_PRO_LSCORE_FIELD.default_value = 0
CMD_C_ADDSCORE_PRO_LSCORE_FIELD.type = 3
CMD_C_ADDSCORE_PRO_LSCORE_FIELD.cpp_type = 2

CMD_C_ADDSCORE_PRO_WSTATE_FIELD.name = "wState"
CMD_C_ADDSCORE_PRO_WSTATE_FIELD.full_name = ".zhajinhua.c2s.CMD_C_AddScore_Pro.wState"
CMD_C_ADDSCORE_PRO_WSTATE_FIELD.number = 2
CMD_C_ADDSCORE_PRO_WSTATE_FIELD.index = 1
CMD_C_ADDSCORE_PRO_WSTATE_FIELD.label = 2
CMD_C_ADDSCORE_PRO_WSTATE_FIELD.has_default_value = false
CMD_C_ADDSCORE_PRO_WSTATE_FIELD.default_value = 0
CMD_C_ADDSCORE_PRO_WSTATE_FIELD.type = 5
CMD_C_ADDSCORE_PRO_WSTATE_FIELD.cpp_type = 1

CMD_C_ADDSCORE_PRO.name = "CMD_C_AddScore_Pro"
CMD_C_ADDSCORE_PRO.full_name = ".zhajinhua.c2s.CMD_C_AddScore_Pro"
CMD_C_ADDSCORE_PRO.nested_types = {}
CMD_C_ADDSCORE_PRO.enum_types = {}
CMD_C_ADDSCORE_PRO.fields = {CMD_C_ADDSCORE_PRO_LSCORE_FIELD, CMD_C_ADDSCORE_PRO_WSTATE_FIELD}
CMD_C_ADDSCORE_PRO.is_extendable = false
CMD_C_ADDSCORE_PRO.extensions = {}
CMD_C_COMPARECARD_PRO_WCOMPAREUSER_FIELD.name = "wCompareUser"
CMD_C_COMPARECARD_PRO_WCOMPAREUSER_FIELD.full_name = ".zhajinhua.c2s.CMD_C_CompareCard_Pro.wCompareUser"
CMD_C_COMPARECARD_PRO_WCOMPAREUSER_FIELD.number = 1
CMD_C_COMPARECARD_PRO_WCOMPAREUSER_FIELD.index = 0
CMD_C_COMPARECARD_PRO_WCOMPAREUSER_FIELD.label = 2
CMD_C_COMPARECARD_PRO_WCOMPAREUSER_FIELD.has_default_value = false
CMD_C_COMPARECARD_PRO_WCOMPAREUSER_FIELD.default_value = 0
CMD_C_COMPARECARD_PRO_WCOMPAREUSER_FIELD.type = 5
CMD_C_COMPARECARD_PRO_WCOMPAREUSER_FIELD.cpp_type = 1

CMD_C_COMPARECARD_PRO.name = "CMD_C_CompareCard_Pro"
CMD_C_COMPARECARD_PRO.full_name = ".zhajinhua.c2s.CMD_C_CompareCard_Pro"
CMD_C_COMPARECARD_PRO.nested_types = {}
CMD_C_COMPARECARD_PRO.enum_types = {}
CMD_C_COMPARECARD_PRO.fields = {CMD_C_COMPARECARD_PRO_WCOMPAREUSER_FIELD}
CMD_C_COMPARECARD_PRO.is_extendable = false
CMD_C_COMPARECARD_PRO.extensions = {}
CMD_C_COMMON_PRO.name = "CMD_C_Common_Pro"
CMD_C_COMMON_PRO.full_name = ".zhajinhua.c2s.CMD_C_Common_Pro"
CMD_C_COMMON_PRO.nested_types = {}
CMD_C_COMMON_PRO.enum_types = {}
CMD_C_COMMON_PRO.fields = {}
CMD_C_COMMON_PRO.is_extendable = false
CMD_C_COMMON_PRO.extensions = {}

CMD_C_AddScore_Pro = protobuf.Message(CMD_C_ADDSCORE_PRO)
CMD_C_Common_Pro = protobuf.Message(CMD_C_COMMON_PRO)
CMD_C_CompareCard_Pro = protobuf.Message(CMD_C_COMPARECARD_PRO)

