-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.gameServer.gameServer.bank.c2s_pb')


WITHDRAW = protobuf.Descriptor();
local WITHDRAW_AMOUNT_FIELD = protobuf.FieldDescriptor();
QUERY = protobuf.Descriptor();

WITHDRAW_AMOUNT_FIELD.name = "amount"
WITHDRAW_AMOUNT_FIELD.full_name = ".gameServer.bank.c2s.Withdraw.amount"
WITHDRAW_AMOUNT_FIELD.number = 1
WITHDRAW_AMOUNT_FIELD.index = 0
WITHDRAW_AMOUNT_FIELD.label = 2
WITHDRAW_AMOUNT_FIELD.has_default_value = false
WITHDRAW_AMOUNT_FIELD.default_value = 0
WITHDRAW_AMOUNT_FIELD.type = 4
WITHDRAW_AMOUNT_FIELD.cpp_type = 4

WITHDRAW.name = "Withdraw"
WITHDRAW.full_name = ".gameServer.bank.c2s.Withdraw"
WITHDRAW.nested_types = {}
WITHDRAW.enum_types = {}
WITHDRAW.fields = {WITHDRAW_AMOUNT_FIELD}
WITHDRAW.is_extendable = false
WITHDRAW.extensions = {}
QUERY.name = "Query"
QUERY.full_name = ".gameServer.bank.c2s.Query"
QUERY.nested_types = {}
QUERY.enum_types = {}
QUERY.fields = {}
QUERY.is_extendable = false
QUERY.extensions = {}

Query = protobuf.Message(QUERY)
Withdraw = protobuf.Message(WITHDRAW)

