-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.gameServer.gameServer.heartBeat.s2c_pb')


HEARTBEAT = protobuf.Descriptor();

HEARTBEAT.name = "HeartBeat"
HEARTBEAT.full_name = ".gameServer.heartBeat.s2c.HeartBeat"
HEARTBEAT.nested_types = {}
HEARTBEAT.enum_types = {}
HEARTBEAT.fields = {}
HEARTBEAT.is_extendable = false
HEARTBEAT.extensions = {}

HeartBeat = protobuf.Message(HEARTBEAT)

