-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.fish.fish.volcano.s2c_pb')


POOLSTATUS = protobuf.Descriptor();
local POOLSTATUS_RATE_FIELD = protobuf.FieldDescriptor();
VOLCANOOPEN = protobuf.Descriptor();
local VOLCANOOPEN_CHAIRID_FIELD = protobuf.FieldDescriptor();
local VOLCANOOPEN_FISHSCORE_FIELD = protobuf.FieldDescriptor();
local VOLCANOOPEN_FISHMULTI_FIELD = protobuf.FieldDescriptor();

POOLSTATUS_RATE_FIELD.name = "rate"
POOLSTATUS_RATE_FIELD.full_name = ".fish.volcano.s2c.PoolStatus.rate"
POOLSTATUS_RATE_FIELD.number = 1
POOLSTATUS_RATE_FIELD.index = 0
POOLSTATUS_RATE_FIELD.label = 2
POOLSTATUS_RATE_FIELD.has_default_value = false
POOLSTATUS_RATE_FIELD.default_value = 0.0
POOLSTATUS_RATE_FIELD.type = 1
POOLSTATUS_RATE_FIELD.cpp_type = 5

POOLSTATUS.name = "PoolStatus"
POOLSTATUS.full_name = ".fish.volcano.s2c.PoolStatus"
POOLSTATUS.nested_types = {}
POOLSTATUS.enum_types = {}
POOLSTATUS.fields = {POOLSTATUS_RATE_FIELD}
POOLSTATUS.is_extendable = false
POOLSTATUS.extensions = {}
VOLCANOOPEN_CHAIRID_FIELD.name = "chairID"
VOLCANOOPEN_CHAIRID_FIELD.full_name = ".fish.volcano.s2c.VolcanoOpen.chairID"
VOLCANOOPEN_CHAIRID_FIELD.number = 1
VOLCANOOPEN_CHAIRID_FIELD.index = 0
VOLCANOOPEN_CHAIRID_FIELD.label = 2
VOLCANOOPEN_CHAIRID_FIELD.has_default_value = false
VOLCANOOPEN_CHAIRID_FIELD.default_value = 0
VOLCANOOPEN_CHAIRID_FIELD.type = 13
VOLCANOOPEN_CHAIRID_FIELD.cpp_type = 3

VOLCANOOPEN_FISHSCORE_FIELD.name = "fishScore"
VOLCANOOPEN_FISHSCORE_FIELD.full_name = ".fish.volcano.s2c.VolcanoOpen.fishScore"
VOLCANOOPEN_FISHSCORE_FIELD.number = 2
VOLCANOOPEN_FISHSCORE_FIELD.index = 1
VOLCANOOPEN_FISHSCORE_FIELD.label = 2
VOLCANOOPEN_FISHSCORE_FIELD.has_default_value = false
VOLCANOOPEN_FISHSCORE_FIELD.default_value = 0
VOLCANOOPEN_FISHSCORE_FIELD.type = 3
VOLCANOOPEN_FISHSCORE_FIELD.cpp_type = 2

VOLCANOOPEN_FISHMULTI_FIELD.name = "fishMulti"
VOLCANOOPEN_FISHMULTI_FIELD.full_name = ".fish.volcano.s2c.VolcanoOpen.fishMulti"
VOLCANOOPEN_FISHMULTI_FIELD.number = 3
VOLCANOOPEN_FISHMULTI_FIELD.index = 2
VOLCANOOPEN_FISHMULTI_FIELD.label = 2
VOLCANOOPEN_FISHMULTI_FIELD.has_default_value = false
VOLCANOOPEN_FISHMULTI_FIELD.default_value = 0
VOLCANOOPEN_FISHMULTI_FIELD.type = 13
VOLCANOOPEN_FISHMULTI_FIELD.cpp_type = 3

VOLCANOOPEN.name = "VolcanoOpen"
VOLCANOOPEN.full_name = ".fish.volcano.s2c.VolcanoOpen"
VOLCANOOPEN.nested_types = {}
VOLCANOOPEN.enum_types = {}
VOLCANOOPEN.fields = {VOLCANOOPEN_CHAIRID_FIELD, VOLCANOOPEN_FISHSCORE_FIELD, VOLCANOOPEN_FISHMULTI_FIELD}
VOLCANOOPEN.is_extendable = false
VOLCANOOPEN.extensions = {}

PoolStatus = protobuf.Message(POOLSTATUS)
VolcanoOpen = protobuf.Message(VOLCANOOPEN)

