customFace = {
    "chat/bq/mmd.png",
    "chat/bq/baonv.png",
    "chat/bq/bukaixin.png",
    "chat/bq/ciya.png",
    "chat/bq/keshui.png",
    "chat/bq/liulei.png",
    "chat/bq/miexiao.png",
    "chat/bq/nvhuo.png",
    "chat/bq/qidao.png",
    "chat/bq/tiaoxin.png",
    "chat/bq/xinsui.png",
    "chat/bq/yundao.png"
}

customQuickMsg = {
    "大家好，很高兴见到各位",
    "和你合作真是太愉快了",
    "快点啊，等得花儿都谢了",
    "你的牌打的也太好了",
    "不要吵不要吵，专心玩游戏吧",
    "怎么又断线，网络怎么这么差啊",
    "不好意思，我要离开一会儿",
    "不要走，决战到天亮",
    "你是MM还是GG",
    "交个朋友吧，能告诉我联系方式吗",
    "再见了，我会想念大家的"
}

customGift = {
    [100]={
        giftName="鸡蛋",
        giftImg="giftLayer/gift_100.png",
        giftCount={1,50,99},
        giftPrefix="eff_jidan"
    },
    [103]={
        giftName="飞刀",
        giftImg="giftLayer/gift_103.png",
        giftCount={1,50,99},
        giftPrefix="eff_dao"
    },
    [104]={
        giftName="炸弹",
        giftImg="giftLayer/gift_104.png",
        giftCount={1,50,99},
        giftPrefix="eff_zhadan"
    },
    [106]={
        giftName="玫瑰",
        giftImg="giftLayer/gift_106.png",
        giftCount={1,50,99},
        giftPrefix="eff_hua"
    },
    [110]={
        giftName="名表",
        giftImg="giftLayer/gift_110.png",
        giftCount={1,50,99},
        giftPrefix="eff_biao"
    },
    [205]={
        giftName="汽车",
        giftImg="giftLayer/gift_205.png",
        giftCount={1,50,99},
        giftPrefix="eff_che"
    },
    [500]={
        giftName="玫瑰",
        giftImg="giftLayer/gift_500.png",
        giftCount={1,50,99},
        giftPrefix="hua"
    },
    [501]={
        giftName="爱心",
        giftImg="giftLayer/gift_501.png",
        giftCount={1,20,50},
        giftPrefix="aixin"
    },
    [502]={
        giftName="扎啤",
        giftImg="giftLayer/gift_502.png",
        giftCount={1,20,50},
        giftPrefix="pijiu"
    },
    [503]={
        giftName="蛋糕",
        giftImg="giftLayer/gift_503.png",
        giftCount={1,20,50},
        giftPrefix="dangao"
    },
    [504]={
        giftName="丘比特",
        giftImg="giftLayer/gift_504.png",
        giftCount={1,20,50},
        giftPrefix="qiubite"
    },
    [505]={
        giftName="金条",
        giftImg="giftLayer/gift_505.png",
        giftCount={1,20,50},
        giftPrefix="jintiao"
    },
    [506]={
        giftName="XO",
        giftImg="giftLayer/gift_506.png",
        giftCount={1,5,7},
        giftPrefix="xo"
    },
    [507]={
        giftName="布加迪",
        giftImg="giftLayer/gift_507.png",
        giftCount={1,2,3},
        giftPrefix="che"
    },

    [508]={
        giftName="臭鸡蛋",
        giftImg="giftLayer/gift_508.png",
        giftCount={1,20,50},
        giftPrefix="jidan"
    },
    [509]={
        giftName="番茄",
        giftImg="giftLayer/gift_509.png",
        giftCount={1,20,50},
        giftPrefix="fanqie"
    },
    [510]={
        giftName="香蕉皮",
        giftImg="giftLayer/gift_510.png",
        giftCount={1,20,50},
        giftPrefix="xiangjiao"
    },
    [511]={
        giftName="大板砖",
        giftImg="giftLayer/gift_511.png",
        giftCount={1,20,50},
        giftPrefix="zhuantou"
    },
    [512]={
        giftName="西瓜",
        giftImg="giftLayer/gift_512.png",
        giftCount={1,20,50},
        giftPrefix="xigua"
    },
    [513]={
        giftName="平底锅",
        giftImg="giftLayer/gift_513.png",
        giftCount={1,50,99},
        giftPrefix="guo"
    },
    [514]={
        giftName="手榴弹",
        giftImg="giftLayer/gift_514.png",
        giftCount={1,5,10},
        giftPrefix="duqidan"
    },
    [515]={
        giftName="炸弹",
        giftImg="giftLayer/gift_515.png",
        giftCount={1,5,10},
        giftPrefix="zhadan"
    },
}