-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.gameServer.gameServer.chat.c2s_pb')


USERCHAT = protobuf.Descriptor();
local USERCHAT_COLOR_FIELD = protobuf.FieldDescriptor();
local USERCHAT_CONTENT_FIELD = protobuf.FieldDescriptor();
USEREXPRESSION = protobuf.Descriptor();
local USEREXPRESSION_EXPRESSID_FIELD = protobuf.FieldDescriptor();
USERMULTIMEDIA = protobuf.Descriptor();
local USERMULTIMEDIA_TYPE_FIELD = protobuf.FieldDescriptor();
local USERMULTIMEDIA_URL_FIELD = protobuf.FieldDescriptor();

USERCHAT_COLOR_FIELD.name = "color"
USERCHAT_COLOR_FIELD.full_name = ".gameServer.chat.c2s.UserChat.color"
USERCHAT_COLOR_FIELD.number = 1
USERCHAT_COLOR_FIELD.index = 0
USERCHAT_COLOR_FIELD.label = 2
USERCHAT_COLOR_FIELD.has_default_value = false
USERCHAT_COLOR_FIELD.default_value = 0
USERCHAT_COLOR_FIELD.type = 13
USERCHAT_COLOR_FIELD.cpp_type = 3

USERCHAT_CONTENT_FIELD.name = "content"
USERCHAT_CONTENT_FIELD.full_name = ".gameServer.chat.c2s.UserChat.content"
USERCHAT_CONTENT_FIELD.number = 2
USERCHAT_CONTENT_FIELD.index = 1
USERCHAT_CONTENT_FIELD.label = 2
USERCHAT_CONTENT_FIELD.has_default_value = false
USERCHAT_CONTENT_FIELD.default_value = ""
USERCHAT_CONTENT_FIELD.type = 9
USERCHAT_CONTENT_FIELD.cpp_type = 9

USERCHAT.name = "UserChat"
USERCHAT.full_name = ".gameServer.chat.c2s.UserChat"
USERCHAT.nested_types = {}
USERCHAT.enum_types = {}
USERCHAT.fields = {USERCHAT_COLOR_FIELD, USERCHAT_CONTENT_FIELD}
USERCHAT.is_extendable = false
USERCHAT.extensions = {}
USEREXPRESSION_EXPRESSID_FIELD.name = "expressID"
USEREXPRESSION_EXPRESSID_FIELD.full_name = ".gameServer.chat.c2s.UserExpression.expressID"
USEREXPRESSION_EXPRESSID_FIELD.number = 1
USEREXPRESSION_EXPRESSID_FIELD.index = 0
USEREXPRESSION_EXPRESSID_FIELD.label = 2
USEREXPRESSION_EXPRESSID_FIELD.has_default_value = false
USEREXPRESSION_EXPRESSID_FIELD.default_value = 0
USEREXPRESSION_EXPRESSID_FIELD.type = 13
USEREXPRESSION_EXPRESSID_FIELD.cpp_type = 3

USEREXPRESSION.name = "UserExpression"
USEREXPRESSION.full_name = ".gameServer.chat.c2s.UserExpression"
USEREXPRESSION.nested_types = {}
USEREXPRESSION.enum_types = {}
USEREXPRESSION.fields = {USEREXPRESSION_EXPRESSID_FIELD}
USEREXPRESSION.is_extendable = false
USEREXPRESSION.extensions = {}
USERMULTIMEDIA_TYPE_FIELD.name = "type"
USERMULTIMEDIA_TYPE_FIELD.full_name = ".gameServer.chat.c2s.UserMultimedia.type"
USERMULTIMEDIA_TYPE_FIELD.number = 1
USERMULTIMEDIA_TYPE_FIELD.index = 0
USERMULTIMEDIA_TYPE_FIELD.label = 2
USERMULTIMEDIA_TYPE_FIELD.has_default_value = false
USERMULTIMEDIA_TYPE_FIELD.default_value = 0
USERMULTIMEDIA_TYPE_FIELD.type = 13
USERMULTIMEDIA_TYPE_FIELD.cpp_type = 3

USERMULTIMEDIA_URL_FIELD.name = "url"
USERMULTIMEDIA_URL_FIELD.full_name = ".gameServer.chat.c2s.UserMultimedia.url"
USERMULTIMEDIA_URL_FIELD.number = 2
USERMULTIMEDIA_URL_FIELD.index = 1
USERMULTIMEDIA_URL_FIELD.label = 2
USERMULTIMEDIA_URL_FIELD.has_default_value = false
USERMULTIMEDIA_URL_FIELD.default_value = ""
USERMULTIMEDIA_URL_FIELD.type = 9
USERMULTIMEDIA_URL_FIELD.cpp_type = 9

USERMULTIMEDIA.name = "UserMultimedia"
USERMULTIMEDIA.full_name = ".gameServer.chat.c2s.UserMultimedia"
USERMULTIMEDIA.nested_types = {}
USERMULTIMEDIA.enum_types = {}
USERMULTIMEDIA.fields = {USERMULTIMEDIA_TYPE_FIELD, USERMULTIMEDIA_URL_FIELD}
USERMULTIMEDIA.is_extendable = false
USERMULTIMEDIA.extensions = {}

UserChat = protobuf.Message(USERCHAT)
UserExpression = protobuf.Message(USEREXPRESSION)
UserMultimedia = protobuf.Message(USERMULTIMEDIA)

