-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.gameServer.gameServer.mission.c2s_pb')


QUERYVOUCHERINFO = protobuf.Descriptor();
local QUERYVOUCHERINFO_DWVOUCHERPOOLTYPE_FIELD = protobuf.FieldDescriptor();

QUERYVOUCHERINFO_DWVOUCHERPOOLTYPE_FIELD.name = "dwVoucherPoolType"
QUERYVOUCHERINFO_DWVOUCHERPOOLTYPE_FIELD.full_name = ".gameServer.mission.c2s.QueryVoucherInfo.dwVoucherPoolType"
QUERYVOUCHERINFO_DWVOUCHERPOOLTYPE_FIELD.number = 1
QUERYVOUCHERINFO_DWVOUCHERPOOLTYPE_FIELD.index = 0
QUERYVOUCHERINFO_DWVOUCHERPOOLTYPE_FIELD.label = 2
QUERYVOUCHERINFO_DWVOUCHERPOOLTYPE_FIELD.has_default_value = false
QUERYVOUCHERINFO_DWVOUCHERPOOLTYPE_FIELD.default_value = 0
QUERYVOUCHERINFO_DWVOUCHERPOOLTYPE_FIELD.type = 5
QUERYVOUCHERINFO_DWVOUCHERPOOLTYPE_FIELD.cpp_type = 1

QUERYVOUCHERINFO.name = "QueryVoucherInfo"
QUERYVOUCHERINFO.full_name = ".gameServer.mission.c2s.QueryVoucherInfo"
QUERYVOUCHERINFO.nested_types = {}
QUERYVOUCHERINFO.enum_types = {}
QUERYVOUCHERINFO.fields = {QUERYVOUCHERINFO_DWVOUCHERPOOLTYPE_FIELD}
QUERYVOUCHERINFO.is_extendable = false
QUERYVOUCHERINFO.extensions = {}

QueryVoucherInfo = protobuf.Message(QUERYVOUCHERINFO)

