-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.gameServer.gameServer.ping.c2s_pb')


PING = protobuf.Descriptor();

PING.name = "Ping"
PING.full_name = ".gameServer.ping.c2s.Ping"
PING.nested_types = {}
PING.enum_types = {}
PING.fields = {}
PING.is_extendable = false
PING.extensions = {}

Ping = protobuf.Message(PING)

