-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol.gameServer.gameServer.jinhuaLottery.c2s_pb')


ADDLOTTERYSCORE = protobuf.Descriptor();
LOTTERYAWARD = protobuf.Descriptor();

ADDLOTTERYSCORE.name = "AddLotteryScore"
ADDLOTTERYSCORE.full_name = ".gameServer.jinhuaLottery.c2s.AddLotteryScore"
ADDLOTTERYSCORE.nested_types = {}
ADDLOTTERYSCORE.enum_types = {}
ADDLOTTERYSCORE.fields = {}
ADDLOTTERYSCORE.is_extendable = false
ADDLOTTERYSCORE.extensions = {}
LOTTERYAWARD.name = "LotteryAward"
LOTTERYAWARD.full_name = ".gameServer.jinhuaLottery.c2s.LotteryAward"
LOTTERYAWARD.nested_types = {}
LOTTERYAWARD.enum_types = {}
LOTTERYAWARD.fields = {}
LOTTERYAWARD.is_extendable = false
LOTTERYAWARD.extensions = {}

AddLotteryScore = protobuf.Message(ADDLOTTERYSCORE)
LotteryAward = protobuf.Message(LOTTERYAWARD)

